# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79e61ac9cc0e030150f0e29cc8d2d79a29e8c47da41c0620d852039be9e9c2f839cefbd1ed219ad26229c376fcea9ff6ab0a772ae7759bb40b64c80e876e0d86

test:
  secret_key_base: b9e28443e122826667628035888630f81cfc0f231b1096998b25a38950aeaaf1435f9c9121d23f5d3c23b0493514d3468c0b8fb97868e860ab4b1a0b08ca96b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
