# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc45a791882c4c7618361cbe94c831d7e1621628f0c1220383579e50626d3f7f0801cdfb235082791ce7c2c4e1ece65d1ef885c9cfe281e69117f92cc9e8196c

test:
  secret_key_base: 481cf7a33b2bd3a7f6effcb0dea7c4d716c5b6bc7d1675640ee4e642edbfd9245f8867306d9f9068614cd7b8bb5b9f9641aa1bf1e88402ce1ad038a0b4df236e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
