# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a8673a397a9593d75928492a9625de5a01a760be60ca83c75cbfb780609cc97cab4297c190e9228212f95490d2cfad453e5a9b7152eb4e4f336d127703ae753

test:
  secret_key_base: 6a6b1732340769fbd3ee609be47e2eb1cc5190e93e3c1d9da8d9bb400084b1f8c9c43081fe1b0f521c5abceff1bcb50235ffafab17e4b96a4d4e7b5f2be8751b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
