# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61f232594b5c3ec6f78265916078bcb039353f417922aba6b8348155b929833fb9aa6a58ac84d3746a5a69371c6ea09059ff4e0847fbc58d0b6985e6c688a2f7

test:
  secret_key_base: f685287e8a4433b78a46d94f4d18679215e482ff05d8a4e542e70505cf573864e0c25c83d5fb41b0968cd20a72e51da56ab26fdf3efcb65fad398039a7ce41b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
